config/routes.rb
Elevators::Application.routes.draw do
  root to: "elevators#index"
  post "/change_configs" => "elevators#change_configs"
  post "/touch_outside" => "elevators#touch_outside", format: :js
  post "/touch_inside" => "elevators#touch_inside", format: :js
  post "/update_state" => "elevators#update_state", format: :js

  mount Resque::Server, :at => "/resque"
end

app/models/elevator.rb
class Elevator  
  attr_reader :num_floors, :state, :direction
  
  IDLE = 1
  RUNNING = 2
  OPENING = 3
  OUT_OF_ORDER = 4

  NONE = 0
  UP = 1
  DOWN = 2
  
  # which floor this elevator should move to
  attr_reader :inside_floors, :outside_floors
  
  # current floor position (could be decimal)
  attr_reader :current_floor
  
  def initialize(num_floors = 15)
    @num_floors = num_floors
    @state = IDLE
    @direction = UP
    @current_floor = 0 # '1' floor
    @inside_floors = []
    @outside_floors = []
  end
  
  def floors_to_go
    (self.inside_floors + self.outside_floors).sort
  end
  
  # trigger when a person touched a floor button inside the elevator
  def touch_button(floor)
    @inside_floors << floor
    @inside_floors.uniq!
  end
  
  # trigger when the system dispatches this target floor to this elevator
  def dispatch_floor(floor)
    @outside_floors << floor
    @outside_floors.uniq!
  end
  
  SPEED_PER_TICK = 0.5 # floor
  
  # after 1 tick (1 second), relocate the current floor
  def tick!
    # do nothing if there's no target floor to go
    if floors_to_go.empty?
      @state = IDLE
      return
    end
    
    # open the elevator if it's just reached one of the target floors
    # Assuming the opening time is 1 tick - The elevator should move on next tick if it has any remaining target floor
    if floors_to_go.include?(@current_floor)
      @state = OPENING
      @inside_floors.delete(@current_floor)
      @outside_floors.delete(@current_floor)
      return
    end

    lowest_floor = floors_to_go.first
    highest_floor = floors_to_go.last

    # relocate the location, depends on target floors & current direction
    @state = RUNNING
    if @current_floor < lowest_floor
      @current_floor = [@current_floor + SPEED_PER_TICK, lowest_floor].min
      @direction = UP
    elsif current_floor > highest_floor
      @current_floor = [@current_floor - SPEED_PER_TICK, highest_floor].max
      @direction = DOWN
    else # lowest_floor < current_floor < highest_floor
      if @state == IDLE
        # If the elevator is idle, pick the shorter direction
        @direction = highest_floor - @current_floor < @current_floor - lowest_floor ? UP : DOWN
      end

      # Follow the current direction
      if @direction == UP
        next_above_floor = floors_to_go.find{|floor| floor > @current_floor}
        throw "Moving up - Something wrong: #{self}" unless next_above_floor
        @current_floor = [@current_floor + SPEED_PER_TICK, next_above_floor].min
      else
        next_below_floor = floors_to_go.reverse.find{|floor| floor < @current_floor}
        throw "Moving down - Something wrong: #{self}" unless next_below_floor
        @current_floor = [@current_floor - SPEED_PER_TICK, next_below_floor].min
      end
    end
  end
end

app/models/elevator_system.rb
class ElevatorSystem
  attr_reader :elevators
  
  def initialize(num_elevators = 2, num_floors = 15)
    @elevators = []
    0.upto(num_elevators - 1).each do
      @elevators << Elevator.new(num_floors)
    end
  end
  
  # trigger when someone waiting for elevator at some floor touch the UP button on the wall
  def touch_up_outside(floor)
    return if floor == @elevators.first.num_floors
    dispatch_touch(floor, Elevator::UP)
  end
  
  # trigger when someone waiting for elevator at some floor touch the DOWN button on the wall
  def touch_down_outside(floor)
    return if floor == 0
    dispatch_touch(floor, Elevator::DOWN)
  end
  
  private

  # Which elevator should receive this target floor
  def dispatch_touch(floor, direction)
    # Find some idle elevator if possible
    idle_elevator = self.elevators.find{ |elevator| elevator.state == Elevator::IDLE }
    if idle_elevator
      idle_elevator.dispatch_floor(floor)
      return
    end
    
    # Find the closest elevator which is moving in the same direction
    closest_elevator = nil
    self.elevators.each do |elevator|
      next if elevator.direction != direction
      if closest_elevator.nil? || (elevator.current_floor - floor).abs < (closest_elevator.current_floor - floor).abs
        closest_elevator = elevator
      end
    end
    if closest_elevator
      closest_elevator.dispatch_floor(floor)
      return
    end
    
    # Last resort: Find the elevator that seems to move to this floor faster
    best_elevator = nil
    best_estimated_time = nil
    self.elevators.each do |elevator|
      estimated_time = (elevator.current_floor - floor).abs / Elevator::SPEED_PER_TICK # time to move
      floors_to_open = elevator.floors_to_go.select{ |f| elevator.direction == Elevator::UP ? (f > floor) : (f < floor) }
      estimated_time += floors_to_open.size # time to open on each target floor before it reaches this 'floor'
      if best_estimated_time.nil? || best_estimated_time > estimated_time
        best_estimated_time = estimated_time
        best_elevator = elevator
      end
    end
    best_elevator.dispatch_floor(floor)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/elevators_controller.rb
require Rails.root + 'app/models/elevator_system'
require Rails.root + 'app/models/elevator'

class ElevatorsController < ApplicationController
  before_filter :load_system
  after_filter :save_system
  def index
    num_elevators = params[:e].try(:to_i) || 2
    num_floors = params[:f].try(:to_i) || 15
    if @system.elevators.size != num_elevators || @system.elevators.first.num_floors != num_floors
      @system = ElevatorSystem.new(num_elevators, num_floors)
    end
  end
  
  def change_configs
    redirect_to root_path(e: params[:e], f: params[:f])
  end
  
  def touch_outside
    floor = params[:floor].try(:to_i) || 0
    direction = params[:direction] || 'up'
    if direction == 'down'
      @system.touch_down_outside(floor)
    else
      @system.touch_up_outside(floor)
    end
    render 'update_state'
  end
  
  def touch_inside
    floor = params[:floor].try(:to_i) || 0
    index = params[:elevator].to_i
    @system.elevators[index].touch_button(floor)
    render 'update_state'
  end
  
  def update_state
  end
  
  private
  def load_system
    @system = Rails.cache.fetch("elevator_system") do
      ElevatorSystem.new
    end
  end
  
  def save_system
    Rails.cache.write("elevator_system", @system)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/elevators/index.html.erb
<style type="text/css">
.left {
  float: left;
}
.clear {
  clear: both;
  padding-top: 10px;
}

.hidden {
  display: none;
}
#outside {
  margin-right: 30px;
}
.outside-floor {
  margin-bottom: 5px;
}
.floor-label {
  display: inline-block;
  width: 60px;
}
.indicator, .legend {
  border: 1px solid #dddddd;
  display: inline-block;
  width: 40px;
  height: 20px;
}
.indicator.idle, .legend.idle {
  background-color: #dddddd;
}
.indicator.opening, .legend.opening {
  background-color: #ffff00;
}
.indicator.running, .legend.running {
  background-color: #ff0000;
}
.elevator {
  border: 1px solid #0000ff;
  display: inline-block;
  width: 90px;
  margin-right: 10px;
  padding: 20px 0px;
  text-align: center;
}
.status {
  font-weight: bold;
  font-size: 18px;
  margin-bottom: 5px;
}
.link-button {
  text-decoration: none;
}
.elevator-button {
  margin: 5px;
  display: inline-block;
  border: 1px solid #dddddd;
  border-radius: 10px;
  width: 30px;
  height: 30px;
  box-sizing: border-box;
  padding: 6px;
  text-align: center;
}
.touched {
  background-color: #ffff00;
}
</style>
<div>
  <h3>Config</h3>
  <%= form_tag change_configs_path do %>
    Number of elevators: <%= text_field_tag "e", params[:e] || 2 %>
    Number of floors: <%= text_field_tag "f", params[:f] || 15 %>
    <%= submit_tag "Change configs" %>
  <% end %>
  <%= link_to "Resque", "/resque" %>
</div>
<div id='outside' class='left'>
  <h2>Outside</h2>
  <% (@system.elevators.first.num_floors - 1).downto(0).each do |i| %>
    <div class='outside-floor'>
      <div class='floor-number hidden'><%= i %></div>
      <div class='floor-label'>Floor <%= i + 1 %>:</div>
      <% @system.elevators.size.times do |j| %>
        <div id='<%= "f#{i}-e#{j}" %>' class='indicator'></div>
      <% end %>
      <% if i < @system.elevators.first.num_floors - 1 %>
        <a href='#' id='<%= "f#{i}-up" %>' class='touch-up-outside'>Up</a>
      <% else %>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      <% end %>
      <% if i > 0 %>
        <a href='#' id='<%= "f#{i}-down" %>' class='touch-down-outside'>Down</a>
      <% end %>
    </div>
  <% end %>
</div>
<div id='inside'>
  <h2>Inside</h2>
  <% @system.elevators.size.times do |j| %>
    <div class='elevator'>
      <div class='elevator-number hidden'><%= j %></div>
      <div class='status' id='<%= "e#{j}-status" %>'></div>
      <% (@system.elevators.first.num_floors - 1).downto(0).each do |i| %>
        <a href='#' id='<%= "e#{j}-f#{i}-button"%>' class='link-button'>
          <div class='floor-number hidden'><%= i %></div>
          <div class='elevator-button'><%= i + 1 %></div>
        </a>
      <% end %>
    </div>
  <% end %>
<div>
<div class='clear'>
  <h3>Legends</h3>
  <div>
    <div class='legend'></div>
    <span>No elevator</span>
    <div class='legend idle'></div>
    <span>Idle</span>
  </div>
  <div>
    <div class='legend opening'></div>
    <span>Opening</span>
    <div class='legend running'></div>
    <span>Running</span>
  </div>
</div>

<script type="text/javascript">
$('.touch-up-outside').click(function() {
  touchOutside(this, 'up');
  return false;
});

$('.touch-down-outside').click(function() {
  touchOutside(this, 'down');
  return false;
});

function touchOutside(that, dir) {
  if ($(that).hasClass('touched')) return;
  $(that).addClass('touched');
  var floor = $(that).prevAll('.floor-number').html();
  $.ajax({
    method: 'POST',
    url: '/touch_outside',
    data: {
      floor: floor,
      direction: dir
    }
  }).done(function(data) {
    data;
  });
}

$('.link-button').click(function() {
  var button = $(this).find('.elevator-button');
  if (button.hasClass('touched')) return false;
  button.addClass('touched');
  var elevator = $(this).prevAll('.elevator-number').html();
  var floor = $(this).find('.floor-number').html();
  $.ajax({
    method: 'POST',
    url: '/touch_inside',
    data: {
      floor: floor,
      elevator: elevator
    }
  }).done(function(data) {
    data;
  });
  return false;
});

$(document).ready(function() {
  $.ajax({
    method: 'POST',
    url: '/update_state'
  }).done(function(data) {
    data;
  });

  setInterval(function() {
    $.ajax({
      method: 'POST',
      url: '/update_state'
    }).done(function(data) {
      data;
    });
  }, 1000);
  
});
</script>

app/views/elevators/update_state.js.erb
$('.elevator-button').removeClass('touched');
$('.indicator').removeClass('idle opening running');
<% @system.elevators.each_with_index do |elevator, j| %>
  <% elevator.num_floors.times do |i| %>
    <% if elevator.inside_floors.include?(i) %>
      $('#' + '<%= "e#{j}-f#{i}-button" %>' + ' .elevator-button').addClass('touched');
    <% end %>
  <% end %>
  
  var statusBar = $('#' + '<%= "e#{j}-status" %>');
  var currentFloor = $('#' + '<%= "f#{elevator.current_floor.to_i}-e#{j}" %>');
  <% if elevator.state == Elevator::IDLE %>
    statusBar.html("IDLE");
    currentFloor.addClass('idle');
  <% elsif elevator.state == Elevator::OPENING %>
    statusBar.html("OPEN");
    currentFloor.addClass('opening');
    $('#' + '<%= "f#{elevator.current_floor.to_i}-up" %>').removeClass('touched');
    $('#' + '<%= "f#{elevator.current_floor.to_i}-down" %>').removeClass('touched');
  <% elsif elevator.state == Elevator::RUNNING %>
    <% if elevator.direction == Elevator::UP %>
      statusBar.html("UP");
    <% else %>
      statusBar.html("DOWN");
    <% end %>
    currentFloor.addClass('running');
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Elevators</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
</head>
<body>

<%= yield %>

</body>
</html>